// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	UserID      int64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
	Title       sql.NullString
	Description sql.NullString
	Done        interface{}
}

type User struct {
	ID       int64
	Username string
	Email    string
}
