name: Deploy
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set/Update configuration
        run: |
          HOSTNAME=$(flyctl status --json | jq -r '.Hostname')
          flyctl secrets set APP_ENV=prod
          flyctl secrets set HOST=$HOSTNAME
          flyctl secrets set PORT=8080
          flyctl secrets set DB_URL=${{ secrets.DB_URL }}
          flyctl secrets set DB_TOKEN=${{ secrets.DB_TOKEN }}
          flyctl secrets set LOG_LEVEL=debug
          flyctl secrets set OAUTH_GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          flyctl secrets set OAUTH_GITHUB_SECRET=${{ secrets.OAUTH_GITHUB_SECRET }}
          echo "Deploying to $HOSTNAME"

      - name: Deploy
        run: flyctl deploy
