name: Deploy
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set/Update configuration
        run: |
          flyctl secrets set APP_ENV=prod \
            HOST=0.0.0.0 \
            PORT=8080 \
            DB_URL=${{ secrets.DB_URL }} \
            DB_TOKEN=${{ secrets.DB_TOKEN }} \
            LOG_LEVEL=debug \
            OAUTH_GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }} \
            OAUTH_GITHUB_SECRET=${{ secrets.OAUTH_GITHUB_SECRET }}

      - name: Deploy
        run: flyctl deploy
